#The name of my pipeline
name: Build and deploy Spring boot app

#when to trigger my workflow
on:
  push:
    - main


jobs:
  build-deploy:
    name: Build and deploy my first spring boot workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "corretto"
          java-version: 17

      - name: Unit tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: |
          mvn clean
          mvn -B package --file pom.xml
